### Press key (Android)
POST http://localhost:3000/session/{{sessionId}}/act
Content-Type: application/json

{ "action": "mobile:pressKey", "key": "Enter" }

### Hide keyboard
POST http://localhost:3000/session/{{sessionId}}/act
Content-Type: application/json

{ "action": "mobile:hideKeyboard" }
