title: WebdriverIO MCP Server
description: Production-grade MCP server for browser and mobile automation
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
search_enabled: true
color_scheme: nil
# Optional: set your repository URL to show GitHub link in the header
# aux_links:
#   "GitHub Repository": https://github.com/your-org/your-repo
logo: 
favicon_ico: 
